parameters:
  name: ''
  platform_name: 'win64'
  mx_buildqual: ''
  working_dir: ''
  staging_dir: ''
  mx_version: ''
  mx_buildnum: ''

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.name }}
    continueOnError: false
    timeoutInMinutes: 0
    variables:
      ROOT_DIR: '${{ parameters.working_dir }}'
      SOURCE_DIR: '$(ROOT_DIR)\mechanica'
      BUILD_ROOT: '$(ROOT_DIR)\mx_condabuild'
      ENV_DIR: '$(BUILD_ROOT)\buildenv'
      BUILD_OUTPUT: '$(BUILD_ROOT)\result'
    workspace:
      clean: all
    steps:

      # Setup
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: Add conda to path
      - script: |
          mkdir $(BUILD_ROOT)
          mkdir $(BUILD_OUTPUT)
        displayName: Create working directories
      - checkout: self
        submodules: recursive
        path: mechanica
        displayName: Get source
      - script: conda create -p $(ENV_DIR) conda-build conda-verify -y
        displayName: Conda setup

      # Build
      - script: |
          call activate $(ENV_DIR)
          set MX_VERSION=$(mx_version)
          set MX_BUILDNUMBER=$(mx_buildnum)
          set MX_BUILDQUAL=${{ parameters.mx_buildqual }}
          conda build -c conda-forge --croot $(BUILD_OUTPUT) $(SOURCE_DIR)\package\conda

      # Conda recipe has built-in tests, so none necessary here

      # Package and publish
      - template: steps-package-publish-conda.yml
        parameters:
          platform_name: 'win64'
          mx_version: $(mx_version)
          staging_dir: ${{ parameters.staging_dir }}
          build_output: $(BUILD_OUTPUT)
