parameters:
- name: platform_name
  type: string
- name: mx_version
  type: string
- name: staging_dir
  type: string
- name: build_output
  type: string
- name: py_versions
  type: object
  default: ['py37', 'py38', 'py39']

steps:
  - ${{ each val in parameters.py_versions }}:
    # Package
    - script: |
        mkdir ${{ parameters.staging_dir }}/${{ val }}

    ${{ if eq(parameters.cuda, 'win64') }}:
      - task: CopyFiles@2
        inputs:
          sourceFolder: '${{ format('{0}\win-64', parameters.build_output) }}'
          contents: '${{ format('mechanica-{0}-{1}*.tar.bz2', parameters.mx_version, val) }}'
          targetFolder: ${{ parameters.staging_dir }}\${{ val }}
          flattenFolders: true
        displayName: Stage python ${{ val }} package
    ${{ elif eq(parameters.cuda, 'linux64') }}:
      - task: CopyFiles@2
        inputs:
          sourceFolder: '${{ format('{0}/linux-64', parameters.build_output) }}'
          contents: '${{ format('mechanica-{0}-{1}*.tar.bz2', parameters.mx_version, val) }}'
          targetFolder: ${{ parameters.staging_dir }}/${{ val }}
          flattenFolders: true
        displayName: Stage python ${{ val }} package
    ${{ elif eq(parameters.cuda, 'osx64') }}:
      - task: CopyFiles@2
        inputs:
          sourceFolder: '${{ format('{0}/osx-64', parameters.build_output) }}'
          contents: '${{ format('mechanica-{0}-{1}*.tar.bz2', parameters.mx_version, val) }}'
          targetFolder: ${{ parameters.staging_dir }}/${{ val }}
          flattenFolders: true
        displayName: Stage python ${{ val }} package

    # Publish
    - publish: ${{ parameters.staging_dir }}/${{ val }}
        artifact: mechanica-${{ parameters.platform_name }}-conda-${{ val }}
        displayName: Publish ${{ val }} package
