parameters:
  platform_name: ''
  mx_version: ''
  staging_dir: ''
  build_output: ''
  - name: py_versions
    type: object
    default: ['py37', 'py38', 'py39']

steps:
  - ${{ each val in parameters.py_versions }}:
    # Package
    - script: |
        mkdir ${{ parameters.staging_dir }}/${{ val }}

    ${{ if eq(parameters.cuda, 'win64') }}:
      - task: CopyFiles@2
        inputs:
          contents: '${{ format('{0}/win-64/mechanica-{1}-{2}*.tar.bz2', ${{ parameters.build_output }}, parameters.mx_version), ${{ val }} }}'
          targetFolder: ${{ parameters.staging_dir }}/${{ val }}
        displayName: Stage python ${{ val }} package
    ${{ elif eq(parameters.cuda, 'linux64') }}:
      - task: CopyFiles@2
        inputs:
          contents: '${{ format('{0}/linux-64/mechanica-{1}-{2}*.tar.bz2', ${{ parameters.build_output }}, parameters.mx_version), ${{ val }} }}'
          targetFolder: ${{ parameters.staging_dir }}/${{ val }}
        displayName: Stage python ${{ val }} package
    ${{ elif eq(parameters.cuda, 'osx64') }}:
      - task: CopyFiles@2
        inputs:
          contents: '${{ format('{0}/osx-64/mechanica-{1}-{2}*.tar.bz2', ${{ parameters.build_output }}, parameters.mx_version), ${{ val }} }}'
          targetFolder: ${{ parameters.staging_dir }}/${{ val }}
        displayName: Stage python ${{ val }} package

    # Publish
    - publish: ${{ parameters.staging_dir }}/${{ val }}
        artifact: mechanica-${{ parameters.platform_name }}-conda-${{ val }}
        displayName: Publish ${{ val }} package
