name: mechanica-docs
channels:
  - conda-forge
  - mechanica
dependencies:
  - python=3.7
  - mechanica
  - ipython
  - notebook
  - ipywidgets
  - ipyevents
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - nbsphinx
  - sphinx-gallery
  - doxygen
  - graphviz
