name: mechanica_develop_$(Data:yyyyMMdd)$(Rev:.r)

trigger:
  - develop

variables:
  py_minor_version: 7
  mx_buildqual: 'develop'

stages:

  # Windows build: local

  - stage: MechanicaBuildWindowsLocal
    displayName: Local build for Windows
    pool:
      vmImage: 'windows-2019'
    dependsOn: []
    strategy:
      matrix:
        Windows Local CPU:
          job_name: MechanicaBuildWindowsLocalCPU
          cuda: false
        Windows Local GPU:
          job_name: MechanicaBuildWindowsLocalGPU
          cuda: true
    - template: .azure-pipelines/job-templates/job-build-test-package-win-local.yml
      parameters:
        name: $(job_name)
        platform_name: 'win64'
        mx_buildqual: $(mx_buildqual)
        py_minor_version: $(py_minor_version)
        working_dir: $(System.DefaultWorkingDirectory)
        staging_dir: $(Build.ArtifactStagingDirectory)
        cuda: $(cuda)

  # Linux build: local

  - stage: MechanicaBuildLinuxLocal
    displayName: Local build for Linux
    pool: 
      vmImage: 'ubuntu-20.04'
    dependsOn: []
    strategy:
      matrix:
        Linux Local CPU:
          job_name: MechanicaBuildLinuxLocalCPU
          cuda: false
        Linux Local GPU:
          job_name: MechanicaBuildLinuxLocalGPU
          cuda: true
    - template: .azure-pipelines/job-templates/job-build-test-package-linux-local.yml
      parameters:
        name: $(job_name)
        platform_name: 'linux64'
        mx_buildqual: $(mx_buildqual)
        py_minor_version: $(py_minor_version)
        working_dir: $(System.DefaultWorkingDirectory)
        staging_dir: $(Build.ArtifactStagingDirectory)
        cuda: $(cuda)

  # MacOS build: local

  - stage: MechanicaBuildMacLocal
    displayName: Local build for Mac
    pool: 
      vmImage: 'macOS-10.11'
    dependsOn: []
    - template: .azure-pipelines/job-templates/job-build-test-package-osx-local.yml
      parameters:
        name: $(job_name)
        platform_name: 'osx64'
        mx_buildqual: $(mx_buildqual)
        py_minor_version: $(py_minor_version)
        working_dir: $(System.DefaultWorkingDirectory)
        staging_dir: $(Build.ArtifactStagingDirectory)
